### PR TITLE
Special-case validation bot bug reports

### PR DESCRIPTION
**Pull request by chadwhitacre**
We invite bot bug reports in the close comment, but then we've been immediately closing the bot bug reports! 😖 https://github.com/getsentry/.github/issues/50 https://github.com/getsentry/.github/issues/49 https://github.com/getsentry/.github/issues/48 https://github.com/getsentry/.github/issues/43 https://github.com/getsentry/.github/issues/39

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Green CI: https://github.com/getsentry/.github-chadwhitacre/actions/runs/593986905.

**Review by billyvg — APPROVED** [review]

**Comment by billyvg** [comment]
Can't access https://github.com/getsentry/.github-chadwhitacre/actions/runs/593986905 btw

**Review by armenzg — APPROVED** [review]
Fun times!

**Comment by chadwhitacre** [comment]
Thanks @armenzg @billyvg, I've given you perms on `.github-chadwhitacre` for future.

**Pull request merged**
