### PR TITLE
fix(template-validator): Normalize CRLF, don't put JSON in comments

### PR DESCRIPTION
**Pull request by BYK**
See example failed issue: getsentry/onpremise#847

### CODE REVIEW

**Review by chadwhitacre — APPROVED** [review]

**Review by chadwhitacre — CHANGES_REQUESTED** [review]
Fails CI due to bad `next` chaining:

https://github.com/getsentry/.github-chadwhitacre/actions/runs/530849327

**Comment by chadwhitacre** [comment]
P.S. JSON in comment body will have snuck in in https://github.com/getsentry/.github/pull/34. 😞

How did we end up thinking about `\r` normalization?

**Comment by chadwhitacre** [comment]
Passes with tests wired right: https://github.com/getsentry/.github-chadwhitacre/runs/1814853753

**Comment by BYK** [comment]
>How did we end up thinking about \r normalization?

When I see some text looking identical and Linux tools claiming they are different, my go to cause is CRLF from Windows. I then went ahead and tried the script locally. Indeed, the line endings were CRLF. Once that was normalized, it works properly.

**Comment by BYK** [comment]
@chadwhitacre fixed the tests, sorry I got confused there. I'll leave the deploy part to you with your bot/script. 😉

**Review by chadwhitacre — APPROVED** [review]

**Pull request merged**
